---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-mcp
  namespace: {{ .Values.global.namespace }}
  labels:
    app: evaluation-mcp
    {{- include "aifeeders.labels" . | nindent 4 }}
spec:
  selector:
    app: evaluation-mcp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
